import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {RoadLighting,nearestRoadLights,ROAD_LIGHT_BUDGET} from '../src/road-lighting.js';
import {CoastTrack} from '../src/track.js';
function fixture(track,s){const q=track.sample(s);return{s,position:track.point(s,9.8,8.7),roadPoint:track.point(s,3.8,.06),heading:q.heading,slope:q.slope};}
function setup(){const track=new CoastTrack(),world={track,scene:new THREE.Scene(),streetLampFixtures:[20,52,84,116,148,180].map(s=>fixture(track,s)),bridgeLampMaterials:[new THREE.MeshStandardMaterial()]};return {world,lights:new RoadLighting(world)};}
test('streetlights automatically illuminate at night and turn off by day within fixed budget',()=>{const {world,lights}=setup(),p=world.track.point(65);lights.update(.3,p,1);assert.equal(lights.stats.activeStreet,3);assert.equal(lights.poolMaterial.uniforms.amount.value,1);assert.ok(lights.street.every(l=>l.intensity>0&&!l.castShadow));assert.equal(world.scene.children.filter(o=>o.isLight).length,4);lights.update(.3,p,0);assert.equal(lights.stats.activeStreet,0);assert.ok(lights.street.every(l=>l.intensity===0));assert.equal(lights.poolMaterial.uniforms.amount.value,0);});
test('pool ignores remote fixtures and reuses nearest slots instead of allocating lights',()=>{const {world,lights}=setup(),p=world.track.point(65);assert.equal(nearestRoadLights(world.streetLampFixtures,p,ROAD_LIGHT_BUDGET.street).length,3);const ids=lights.street.map(l=>l.uuid);lights.update(.3,new THREE.Vector3(3000,100,3000),1);assert.equal(lights.stats.activeStreet,0);assert.deepEqual(lights.street.map(l=>l.uuid),ids);});
test('one nearby traffic headlight follows heading and switches off when no cars are visible',()=>{const {lights}=setup(),root=new THREE.Group();root.position.set(5,22,10);root.rotation.y=Math.PI/2;root.updateMatrixWorld(true);lights.updateTraffic([{mesh:{root}}],new THREE.Vector3(0,22,0),1);assert.equal(lights.stats.activeTraffic,1);assert.ok(lights.traffic.target.position.x>40);assert.equal(lights.traffic.castShadow,false);root.visible=false;lights.updateTraffic([{mesh:{root}}],new THREE.Vector3(),1);assert.equal(lights.stats.activeTraffic,0);assert.equal(lights.traffic.intensity,0);});
