"""Build the repaired Aholo GT into an isolated candidate directory.

Blender 5.2 background usage:
    blender --background --python-exit-code 1 --python tools/prepare-lux-car.py
    blender ... --python tools/prepare-lux-car.py -- --out-dir output/my-candidate

The stable, retained Aholo canopy/axle/plate package is checked in. Exterior
panels are generated by rebuild-lux-panels.py. Publishing the candidate is a
separate validation/promotion operation; this entry point never writes public/.
"""
import runpy
from pathlib import Path

if __name__ == '__main__':
    runpy.run_path(str(Path(__file__).with_name('rebuild-lux-panels.py')),run_name='__main__')
